### ISSUE TITLE
Generar la página de inicio (tribunal, normas, calendario, documentos).

### ISSUE THREAD

**Issue by jfb0019** [jfb0019/Gestor-TFG-2016#8]

**Comment by jfb0019** [comment]
Aplicación desplegada en [Openshift](https://tomcat8-vaadinjfb.rhcloud.com/sistinf-0.1/)

**Comment by clopezno** [comment]
- Coger calendario del fichero de configuración
- Añadir una propiedad con los años de comienzo del curso
